<?php

namespace SKCMS\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategoryRepository extends EntityRepository
{
}
